version: '3.8'

services:
  database:
    image: postgres:13.1
    container_name: demo_db
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: demo
    ports:
      - 5432:5432

# docker exec -it demo_db psql -U postgres -d demo
